### ISSUE TITLE
does not work!

### ISSUE THREAD

**Issue by mtabdar** [rsinghal26/My-secret-diary-#3]
hi, i tried your diary but cannot make it work.
1- please put your database script or a sample sql of database here
2- it seems you use only one table (users ) with 4 columns -id, email,password and message, i created it and sign up part of your code works but login doesn't. 
3- the site also doesn't work!
thanks

**Comment by duocodies** [comment]
@rsinghal26

**Comment by rsinghal26** [comment]
SQL file added for database reference.

**Comment by AlphaDG** [comment]
Nothing better than the creator to only reply for ONE of the problems your having, a year and a half later. There are other problems, like the 'logout' button is totally non-operational. Could just be really old code, but its from 2021, so it should work. Maybe it was browser specific, bad idea.

If you change the 'logout' button in 'loggedinpage.php  FORM to **action="index.php" method="post"**, and the button, add  **name="logout" value="1"**, and remove the a href... (leave the "Log Out" text there)
In 'index.php', replace  **if(array_key_exists("logout", $_GET)){** with **if(isset($_POST['logout']) && $_POST['logout'] =="1") {**, then you can 'log out'. The 'stayloggedin' (Remember Me checkbox) does not work either.

The auto-save to DB, of anything you type into the 'message' is a cool idea, but confusing because people are use to a 'Save' button. Maybe a banner across the top of the textarea, stating 'Auto-Saved at 00:00:00' would be a great idea, and only auto-save every 5-10 seconds.
